bot:
  token: telegram-bot-token
  admins: [682000000, 682000000, 682000000]

itemshop:
  channel: -1001001001001
  primary_title: ""
  primary_price: 1
  primary_currency: V-Bucks
  secondary_title: "خريد"
  secondary_price: 60
  secondary_currency: T # Stands for "Tomans"
