TelegramBot:
  CachePath: ./cache
  APIID: "XXXXXXX"
  APIHash: MyAPIHash
  BotToken: MyBotToken
  SuperUsers: [682785614, 667442892]
  Admins: [561812392]

Itemshop:
  Channel: -1001606477591
  PriceLegal: 100
  PriceIllegal: 60
