#!/bin/fish

echo "Removing old folder..."
sudo rm -rf /var/lib/lxd/storage-pools/default/containers/llamanite/rootfs/root/AccountLandBot

echo "Copying new folder..."
sudo cp -r ../AccountLandBot/ /var/lib/lxd/storage-pools/default/containers/llamanite/rootfs/root/

echo "Building..."
lxc exec llamanite -- sudo --login --user root fish -ilc "cd ./AccountLandBot && go build ."

echo "Getting New Build..."
sudo cp /var/lib/lxd/storage-pools/default/containers/llamanite/rootfs/root/AccountLandBot/accountland ./


echo "Done!"